---
title: "Projetos"
output:
  blogdown::html_page
---

# <font color="#006600", size = 5> Veraz </font>

Em sua descrição o [Portal da Transparência](http://www.portaltransparencia.gov.br/) 
afirma que, através da sua plataforma, o cidadão comum é capaz de se informar a 
respeito da utilização do dinheiro público. Contudo, o grande volume de dados e 
sua estrutura são obstáculos para pessoas não familiarizadas com tecnologia da 
informação. Portanto, o intuito do projeto Veraz é romper essas barreiras 
disponibilizando informações e análise dos gastos públicos de maneira 
compreensível e detalhada.

Atualmente o projeto conta com um blog que pode ser acessado através
deste [link](https://stats4good.github.io/veraz).

# <font color="#a31aff", size = 5> GESEM </font>

Em 2016, segundo os dados do SINAN (Sistema de Informação de Agravos de 
Notificação), foi registrado no Brasil um caso de estupro a cada 23 minutos. 
Apesar disso, estima-se que apenas 10% dos casos ocorridos são registrados 
(IPEA, 2014). Sabe-se também que em 89,18% do que foi notificado, as vítimas 
foram mulheres e, além disso, em quase metade destes, eram crianças com menos 
de 14 anos. Um fato que torna a situação ainda mais grave é que  em quase 70% 
dos crimes, a vítima conhecia o agressor. Assim, tendo como base essas alarmantes 
estatísticas relacionadas ao estupro, o objetivo principal do GESEM é estudar a 
subnotificação da quantidade de casos de estupro em mulheres no Brasil, assim como 
fatores culturais, demográficos, econômicos e sociais relacionados ao crime.

Atualmente o projeto conta com um blog que pode ser acessado através
deste [link](https://stats4good.github.io/gesem).